version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bibichanel/app:latest
    container_name: webapp
    entrypoint: ["./wait.sh"]
    depends_on:
      - database
    links:
      - 'database:db'
    ports:
      - "8000:8000"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3 

  database:
    image: mysql:latest
    container_name: mysql-server
    env_file:
      - ./mysql/database.env
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
    links:
      - 'database:db'
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
